// react-cli/src/App.tsx
import React, { Suspense, lazy } from 'react'
import { Link, Routes, Route } from 'react-router-dom'
import { Button } from 'antd'
// import Home from './pages/Home'
// import About from './pages/About'

const Home = lazy(() => import(/* webpackChunkName: 'home' */ './pages/Home'))
const About = lazy(() => import(/* webpackChunkName: 'about' */ './pages/About'))

function App() {
  return (
    <div>
      <Button type='primary'>测试</Button>
      <h1>123456</h1>
      <ul>
        <li>
          <Link to='/home'>Home</Link>
        </li>
        <li>
          <Link to='/about'>About</Link>
        </li>
      </ul>
      <Suspense fallback={<div>loading</div>}>
        <Routes>
          <Route path='/home' element={<Home />} />
          <Route path='/about' element={<About />} />
        </Routes>
      </Suspense>
    </div>
  )
}
export default App

// vue-cli/src/App.vue
<template>
  <div>Vue</div>
  <el-button type="primary">点击</el-button>
  <ul>
    <li>
      <router-link to="/home">Home</router-link>
    </li>
    <li>
      <router-link to="/about">About</router-link>
    </li>
  </ul>
  <router-view />
</template>

<script setup lang="ts"></script>

<style scoped></style>
